# 设备信息
device:
  ser: COM3          # 蓝牙模块串口号
  pid: AC15188261E0  # 设备PID号

# 手动模式亮度配置，对应PPFD值
dimconfig:
  dim10: 50            # 10% 亮度对应的 PPFD 值
  dim20: 100           # 20% 亮度对应的 PPFD 值
  dim30: 120           # 30% 亮度对应的 PPFD 值
  dim40: 130           # 40% 亮度对应的 PPFD 值
  dim50: 140           # 50% 亮度对应的 PPFD 值
  dim60: 150           # 60% 亮度对应的 PPFD 值
  dim70: 160           # 70% 亮度对应的 PPFD 值
  dim80: 170           # 80% 亮度对应的 PPFD 值
  dim90: 180           # 90% 亮度对应的 PPFD 值
  dim100: 190          # 100% 亮度对应的 PPFD 值


# 手动模式下，PPFD差值浮动范围设置
# 示例：30 表示 PPFD 正负 30 的浮动范围
margins:
  margin: 30

# 自动模式配置：st和et设置时需要间隔三分钟
autoParams:
  st: 960               # 开始时间，分钟为单位
  et: 963               # 结束时间，分钟为单位
  dim: 50               # 亮度百分比
  darkenT: 45           # 开始变暗温度，范围:15 ~ 45
  offT:  50             # 关闭温度，范围:15 ~ 50


# PPFD模式配置：st和et设置时需要间隔十分钟
ppfdParams:
  st: 960                       # 开始时间，分钟为单位
  et: 970                       # 结束时间，分钟为单位
  dim_min: 50                   # 最小亮度百分比
  dim_max: 100                  # 最大亮度百分比
  ppfd: 320                     # PPFD值
  darkenT: 45                   # 开始变暗温度，范围:15 ~ 45
  offT: 50                      # 关闭温度，范围:15 ~ 50
  sunTime: 0                    # 日出日落时间，范围:0 ~ 30