# 设备信息
device:
  ser: COM3          # 蓝牙模块串口号
  pid: AC15188261E0  # 设备PID号

# 手动调节开关孔位模式，执行次数
switch_times: 5
# 手动模式下，PPFD差值浮动范围设置
# 示例：30 表示 PPFD 正负 30 的浮动范围
margins:
  margin: 30

# 手动模式亮度配置，对应PPFD值
dimconfig:
  dim10: 286            # 10% 亮度对应的 PPFD 值
  dim20: 420           # 20% 亮度对应的 PPFD 值
  dim30: 550           # 30% 亮度对应的 PPFD 值
  dim40: 680           # 40% 亮度对应的 PPFD 值
  dim50: 806           # 50% 亮度对应的 PPFD 值
  dim60: 932           # 60% 亮度对应的 PPFD 值
  dim70: 1055           # 70% 亮度对应的 PPFD 值
  dim80: 1176           # 80% 亮度对应的 PPFD 值
  dim90: 1295           # 90% 亮度对应的 PPFD 值
  dim100: 1396          # 100% 亮度对应的 PPFD 值